collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3122029753867537
  brandStrength: 0.24720647116191685
  lightness: 0.9992443649098277
  brandColors:
    - '#334D5C'
    - '#45B29D'
    - '#EFC94C'
    - '#E27A3F'
    - '#DF5A49'
  rhythmicContrast: 0.14759709173813462
typography_spectrum: 0.43828415824100375
layout_spectrum: 0.33180333860218525
name: BPO
