collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.9245816108305007
color:
  saturation: 0.7193736
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#4E78A6'
    - '#B87C72'
    - '#1D9EA4'
    - '#402B28'
    - '#013E39'
  rhythmicContrast: 0.08621652
layout_spectrum: 0.1872986946254969
name: BPO
